---
title: "R Notebook"
output: html_notebook
---

```{r}

set.seed(1337)

if (!requireNamespace("neha", quietly = TRUE)){
  if (!requireNamespace("devtools", quietly = TRUE)){
    install.packages("devtools")
  }
  devtools::install_github("desmarais-lab/neha")
  library(neha)
}

library(neha)
library(tidyverse)
library(haven)

boushey2016_full <- read_dta("C:/Users/ndhem/Documents/vscode_projects/Pred_Diffusion_2025/data/boushey2016.dta")

```

```{r}

# Covariates
covariates <- c("policycongruent","gub_election","elect2", "hvd_4yr", "fedcrime",
                "leg_dem_per_2pty","dem_governor","insession","propneighpol",
                "citidist","squire_prof86","citi6008","crimespendpc","crimespendpcsq",
                "violentthousand","pctwhite","stateincpercap","logpop",
                "counter","counter2","counter3")

# Subset and drop missing
boushey2016 <- boushey2016_full %>%
  select(state, year, billnum, dvadopt, all_of(covariates)) %>%
  na.omit()

# Define formula
formula <- as.formula(
  paste("dvadopt ~", paste(covariates, collapse = " + "))
)

# Fit logistic regression model
logistic <- glm(formula, data = boushey2016, family = binomial(link = "logit"))

# Extract coefficients
coef_vec <- coef(logistic)

# Get design matrix X
X <- model.matrix(formula, data = boushey2016)

# Drop intercept
coef_matrix <- as.matrix(coef_vec[-c(1), drop = FALSE])

```

```{r}

simulate_neha_discrete2 <- function(x,node,time,beta,gamma,a=-8){
  times <- sort(unique(x[,time]))
  nodes <- sort(unique(x[,node]))
  x_linear_predictor <- as.matrix(x[,row.names(beta)])%*%beta
  event_times <- rep(NA,length(nodes))
  source <- do.call('rbind',strsplit(rownames(gamma),"_"))[,1]
  follower <- do.call('rbind',strsplit(rownames(gamma),"_"))[,2]
  event <- rep(NA,nrow(x))
  for(t in times){
    nodes_at_risk <- nodes[is.na(event_times)]
    for(n in nodes_at_risk){
      
      idx <- which((x[, time] == t) & (x[, node] == n))
      if (length(idx) == 0) {
        message("Skipping missing ", n, "-", t)
        next
      }
      if (length(idx) > 1) {
        # Just take the first one (or handle aggregation here)
        idx <- idx[1]
      }
      xlp_nt <- x_linear_predictor[which((x[,time]==t) & (x[,node]==n))]
      n_sources <- source[which(follower==n)]
      source_effects <- gamma[which(follower==n),1]
      source_times <- event_times[match(n_sources,nodes)]
      # a = .25
      # plot(0:20,exp(a*-(0:20)),ylim=c(0,1))
      time_effects <- source_effects*exp(-exp(a)*(t-source_times))
      time_effects <- time_effects[which(!is.na(time_effects))]
      linear_predictor <- xlp_nt
      if(length(time_effects)>0){
        linear_predictor <- linear_predictor + sum(time_effects)
      }
      pr_nt <- 1/(1+exp(-linear_predictor))
      event_nt <- 1*(pr_nt > runif(1))
      event[which((x[,time]==t) & (x[,node]==n))] <- 0
      if(event_nt==1){
        event_times[which(nodes==n)] <- t
        event[which((x[,time]==t) & (x[,node]==n))] <- 1
      }
    }

  }
  x <- data.frame(x,event,stringsAsFactors=F)
  data.frame(na.omit(x),stringsAsFactors=F)
}

```

```{r}

# Problems arise when not all states have the same starting year
# This is an error with the original datasets; some authors do not have perfect data

sim_results <- data.frame()

for (bill in unique(boushey2016$billnum)){
  # Covariates
  covariates <- c("policycongruent", "gub_election", "elect2", "hvd_4yr", "fedcrime",
                "leg_dem_per_2pty", "dem_governor", "insession", "propneighpol",
                "citidist", "squire_prof86", "citi6008", "crimespendpc", "crimespendpcsq",
                "violentthousand", "pctwhite", "stateincpercap", "logpop",
                "counter", "counter2", "counter3")
  
  # Subset and drop missing
  boushey2016 <- boushey2016_full %>%
    select(state, year, billnum, dvadopt, all_of(covariates)) %>%
    na.omit()
  
  # Filter data per bill
  policy_data <- boushey2016 %>% filter(billnum == bill)
  policy_data <- as.data.frame(policy_data)
  
  # Select relevant data
  policy_data <- policy_data %>% select(state, year, all_of(covariates))
  
  # Create fake gamma
  tie_names <- c("california_montana", "minnesota_wisconsin", "iowa_minnesota")
  tie_values <- c(0.8, 0.5, 0.3)
  gamma <- matrix(tie_values, ncol = 1, dimnames = list(tie_names, "value"))
  
  sim_data <- simulate_neha_discrete2(policy_data, node = "state", time = "year", beta = coef_matrix, gamma = gamma, a = 0)
  
  # Add bill name column
  sim_data$billnum <- bill
  
  # Aggregate results
  sim_results <- bind_rows(sim_results, sim_data)
  
}

```

```{r}

# # Select one bill
# bill = 4
# 
# # Covariates
# covariates <- c("policycongruent", "gub_election", "elect2", "hvd_4yr", "fedcrime",
#                 "leg_dem_per_2pty", "dem_governor", "insession", "propneighpol",
#                 "citidist", "squire_prof86", "citi6008", "crimespendpc", "crimespendpcsq",
#                 "violentthousand", "pctwhite", "stateincpercap", "logpop",
#                 "counter", "counter2", "counter3")
# 
# boushey2016 <- boushey2016_full %>%
#   select(state, year, billnum, dvadopt, all_of(covariates)) %>%
#   na.omit()
#   
# # Filter data per bill
# policy_data <- boushey2016 %>% filter(billnum == bill)
# policy_data <- as.data.frame(policy_data)
# # Check unique state-year combination
# # d <- policy_data %>% count(state, year) %>% filter(n > 1)
# # unique(policy_data$state)
# 
# # Create fake gamma
# tie_names <- c("california_montana", "minnesota_wisconsin", "iowa_minnesota")
# tie_values <- c(0.8, 0.5, 0.3)
# gamma <- matrix(tie_values, ncol = 1, dimnames = list(tie_names, "value"))
# 
# # Run simulation
# sim_data <- simulate_neha_discrete2(policy_data, node = "state", time = "year", beta = coef_matrix, gamma = gamma, a = 0)

```
