#PBS -l nodes=1:ppn=20
#PBS -l walltime=48:00:00
#PBS -l mem=120gb
#PBS -j oe
#PBS -mae bdesmarais@psu.edu
#PBS -N boushey_rep

cd /gpfs/group/bbd5087/default/boushey_analysis
  
  module load r/3.4

module load python/3.6.3-anaconda5.0.1
conda create -n rJava
source activate rJava
conda install -c conda-forge r-rjava
module load python/3.6.3-anaconda5.0.1
source activate rJava

R CMD BATCH replication.R


